# Uso de libreria NUMPY
En este cuaderno voy a practicar el uso de la libreria NUMPY

In [3]:
#Importar la libreria a nuestro entorno de trabajo
import numpy as np

### Colecciones de datos en NUMPY

In [ ]:
d1 = np.array([97,98,99,100]) #Arreglo de una sola dimensión 
d1 

array([ 97,  98,  99, 100])

In [ ]:
d2 = np.array([(1.11,2.22,3.33), (4.44,5.55,6.66)], dtype = float) #Arreglo de dos dimensiones, similar a una tabla 
print(d2)

[[1.11 2.22 3.33]
 [4.44 5.55 6.66]]


In [ ]:
d3 =  c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float) #Arreglo de tres dimensiones
d3

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Funciones con NUMPY

In [ ]:
print(d1.shape) #Longitud del arreglo
print(d2.shape)

(4,)
(2, 3)


In [ ]:
#Imprimir solo ciertos elementos de un arreglo, en este caso al ser de dos dimensiones se especifica la fila y la columna
print(d2[0,1],d2[1,0]) #Se pueden imprimir multiples elementos en una sola intrucción 

2.22 4.44


In [ ]:
#Cambiar el valor de un elemento 
d2[1,2] = 6.6666

In [ ]:
d2 #Visualizar el nuevo arreglo

array([[1.11  , 2.22  , 3.33  ],
       [4.44  , 5.55  , 6.6666]])

### Operaciones en arreglos

In [4]:
a = np.array([12,15,34,22,55,43,56,33,12,77]) #Arreglo con valores introducidos de manera manual
b = np.random.randint(1,100,(10)) #Arreglo generado con 10 valores aleatorios
print("a = {}".format(a))
print("b = {}".format(b))

a = [12 15 34 22 55 43 56 33 12 77]
b = [93 31 51 50 19 57 91 78 74 75]


In [5]:
#Pueden realizarse las operaciones aritmeticas basicas, deben ser realizadas entre dos arreglos de la misma longitud
print("Suma (+) = {}".format(np.add(a,b)))
print("Resta (-) = {}".format(np.subtract(b,a)))#El orden en la resta y división son importantes para obtener el resultado deseado
print("Multiplicación (*) = {}".format(np.multiply(a,b)))
print("División (/) = {}".format(np.divide(b,a))) 

Suma (+) = [105  46  85  72  74 100 147 111  86 152]
Resta (-) = [ 81  16  17  28 -36  14  35  45  62  -2]
Multiplicación (*) = [1116  465 1734 1100 1045 2451 5096 2574  888 5775]
División (/) = [7.75       2.06666667 1.5        2.27272727 0.34545455 1.3255814
 1.625      2.36363636 6.16666667 0.97402597]


In [17]:
#Tambien se puede realizar algunas operaciones de estadistica básicas en arreglos
print("Valor MAX = {}".format(b.max()))
print("Valor MIN = {}".format(b.min()))
print("Promedio = {}".format(b.mean()))
print("Desviación estándar = {}".format(b.std()))
print("")
print("Suma total del arreglo = {}".format(b.sum()))
print("Suma acumulativa del arreglo = {}".format(b.cumsum()))


Valor MAX = 93
Valor MIN = 19
Promedio = 61.9
Desviación estándar = 23.389955108977873

Suma total del arreglo = 619
Suma acumulativa del arreglo = [ 19  50 100 151 208 282 357 435 526 619]
